apiVersion: v1
kind: Service
metadata: 
  name: svc-pod-1
spec:
  type: NodePort
  selector:
    app: primeiro-pod
  ports:
   - port: 80
     #nodePort: 30000-32767
     nodePort: 30000
    # targetPort: 80
      